# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/page/userguide/cmd_ci.html >
#
#
# Please choice one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#


#
# Template #1: General project. Test it using existing `platformio.ini`.
#

language: python
python:
    - "2.7"

dist: trusty
sudo: required

cache:
    directories:
        - "~/.platformio"

env:
  global:
    - PLATFORMIO_CI_SRC=MainBrain/src/
    - secure: PT/yrofGQmhzTc1XmGh3JpaVIyskiW7EIW6M7Sudfzl7Pv/NT5qe4U9IWBT1yynGgRheJeTjUVyft9Fq5dGSPckH+BuihGZcZlKdQWelHxX4jekgkIo5j91XUut9NUOoFI3+CaopbLUx7Kx0Zjv0UlY/vi3C5ucf3WtupYEiCUlJJNAWfoIbrfDHbUsdsCI+weVySb7d9DNBc7q7NvFV/R9/P0MqdG+lkY7Ns76WgPTYNlJCLFEi17u5jbtNOf6ffmZht/RCbp2M+sl7WF3WMGjalNweMlJF3QZ+tPqqsUN/Zh1W3cQv1H1iNqQwuaNUTudTQHiUbfNV5PI+DwkfUs8c2BAU6a60tGviE44MNUaFruuDz60UiETON4XHSUcfUQxrkcMCYombcltfs6tJWkHT3KpsLrcKJCIPtsmaYM4beVIuwTfs6iom9TWJTNsQmRHV7/Lzpf9DVBViOX31/SWS/+CcDFzZMdXLmjpeNP4fPQ9D68PUQyRzcP2xLpz0JQyHDyX9Wq1n/yVccHJ7JmqqWHwBXhR0tBaFk5AdlagNT/Y5j/QQe0M+JJJ1a1diaeol58qgkA/iiGeUD7s6u2WsXs/+BHIkdtE7wD6nR2rgC0jdxayxSZ915fjvyCTbgiwA1pc7Umjm6ZdWmnqKcWuDJliWKSlNSjS8q5sNJtU=

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install cppcheck

install:
    - pip install -U platformio
    - platformio update

    # Libraries from PlatformIO Library Registry:
    #
    # https://platformio.org/lib/show/322/SdFat
    - platformio lib -g install 322

    # https://platformio.org/lib/show/942/U8g2
    - platformio lib -g install 942

script:
    - echo "Building project for Teensy 3.6"
    - platformio ci --board=teensy36

    # - echo "List remote devices"
    # - platformio remote device list

    # - echo "Run embedded test on remote Teensy 3.6"
    # - platformio remote test --project-dir MainBrain/

notifications:
    slack: 
        rooms: 
            - electriccarteam:asuKUGdj8PTljANmYngSspek#builds
        on_success: change
        on_failure: always
